### ISSUE TITLE
`plot_settings.yaml` is lost in non-editable installs

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/pint_pal#90]
If PINT Pal is installed as
```
pip install git+https://github.com/nanograv/pint_pal.git
```
the file `plot_settings.yaml` doesn't get copied to the install directory, which leads to errors like
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.local/lib/python3.10/site-packages/pint_pal/plot_settings.yaml'
```

A temporary workaround is to use an editable install (clone the entire repo and do `pip install -e .`), but it should be possible to fix this by adding `plot_settings.yaml` to the package data in `pyproject.toml`.

**Comment by golamshaifullah** [comment]
I have this here: https://github.com/golamshaifullah/pint_pal/tree/patch-plot-settings-yaml but it doesn't look like I can raise  a PR....
